// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNeaP6EsQhZsl5VHzD3XS2YDwWOu1fzHs',
    appId: '1:1000748384094:android:550cee4b3082e20b4f19cf',
    messagingSenderId: '1000748384094',
    projectId: 'smartbed-c3b9e',
    storageBucket: 'smartbed-c3b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9v1Lprak7rA4XcNbKqqprJAUh_lKy0v4',
    appId: '1:1000748384094:ios:29b3354a714159e64f19cf',
    messagingSenderId: '1000748384094',
    projectId: 'smartbed-c3b9e',
    storageBucket: 'smartbed-c3b9e.appspot.com',
    iosClientId: '1000748384094-qkqr966sd54uc3jj5pbtfhdau08kole2.apps.googleusercontent.com',
    iosBundleId: 'com.technion.smartbed',
  );
}
